# docker/Dockerfile.web
FROM node:20-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY apps/web/package*.json ./
COPY packages/ ../packages/

# Installer les dépendances
RUN npm install

# Copier le code source
COPY apps/web/ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]