# Clerk
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_...
CLERK_SECRET_KEY=sk_test_...
CLERK_WEBHOOK_SIGNING_SECRET=whsec_...
NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard

# API Backend
NEXT_PUBLIC_API_URL=http://localhost:5000/api

# Site
NEXT_PUBLIC_SITE_URL=http://localhost:3000

# UploadThing
UPLOADTHING_TOKEN=...